### ISSUE TITLE
Error when starting Eclipse (Cannot invoke "String.length()" because "this.input" is null)

### ISSUE THREAD

**Issue by rkurman** [hiconic-os/com.braintribe.devrock.eclipse#4]
Every time when I start Eclipse, I get the error message: "Cannot invoke "String.length()" because "this.input" is null"

The underlying Exception is this:

```java
java.lang.NullPointerException: Cannot invoke "String.length()" because "this.input" is null
	at java.base/java.net.URI$Parser.parse(URI.java:3186)
	at java.base/java.net.URI.<init>(URI.java:645)
	at java.base/java.net.URI.create(URI.java:930)
	at org.apache.http.client.methods.HttpGet.<init>(HttpGet.java:66)
	at com.braintribe.devrock.mc.core.configuration.BasicArtifactChangesSynchronization.getResponse(BasicArtifactChangesSynchronization.java:128)
	at com.braintribe.devrock.mc.core.configuration.BasicArtifactChangesSynchronization.getRavenhurstResponse(BasicArtifactChangesSynchronization.java:137)
	at com.braintribe.devrock.mc.core.configuration.BasicArtifactChangesSynchronization.queryContents(BasicArtifactChangesSynchronization.java:174)
	at com.braintribe.devrock.bridge.eclipse.internal.InternalMcBridge.retrieveCurrentRemoteArtifactPopulation(InternalMcBridge.java:262)
	at com.braintribe.devrock.bridge.eclipse.ScopingMcBridge.lambda$9(ScopingMcBridge.java:145)
	at com.braintribe.devrock.bridge.eclipse.ScopingMcBridge.doWork(ScopingMcBridge.java:75)
	at com.braintribe.devrock.bridge.eclipse.ScopingMcBridge.retrieveCurrentRemoteArtifactPopulation(ScopingMcBridge.java:145)
	at com.braintribe.devrock.plugin.DevrockPlugin.retrieveCurrentRemoteArtifactPopulation(DevrockPlugin.java:302)
	at com.braintribe.devrock.importer.dependencies.listener.ParallelRepositoryScanner.scanAndStorePopulation(ParallelRepositoryScanner.java:90)
	at com.braintribe.devrock.importer.dependencies.listener.ParallelRepositoryScanner.rescan(ParallelRepositoryScanner.java:74)
	at com.braintribe.devrock.importer.dependencies.listener.ScanControl.lambda$0(ScanControl.java:56)
	at org.eclipse.core.runtime.jobs.Job$1.run(Job.java:166)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

**Comment by rkurman** [comment]
I was using an outdated update site. After switching to https://eclipse.hiconic-os.org/beta/, the error is gone.
